# Generated by Django 5.0.7 on 2024-12-01 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_booking_booking_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='sedancar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.CharField(blank=True, max_length=5, null=True)),
                ('image', models.ImageField(upload_to='image/')),
            ],
        ),
    ]
