# Generated by Django 5.0.7 on 2024-12-02 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_sedancar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sedancar',
            name='image',
        ),
    ]
