# Generated by Django 5.1.6 on 2025-02-28 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_sedancar_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='drive',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='fare',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='total',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
