# Generated by Django 5.1.6 on 2025-02-28 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_booking_drive_booking_fare_booking_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='carType',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
