# Generated by Django 5.1.6 on 2025-02-28 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_booking_cartype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='carType',
            new_name='driverCharge',
        ),
    ]
