# Generated by Django 5.1.6 on 2025-03-01 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_booking_cartype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
