# Generated by Django 5.1.6 on 2025-03-04 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_booking_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='time',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
