# Generated by Django 5.1.6 on 2025-03-06 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_roundtrip_delete_roundmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roundtrip',
            name='time',
        ),
    ]
