# Generated by Django 5.1.6 on 2025-03-06 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_remove_roundtrip_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roundtrip',
            name='carType',
        ),
        migrations.RemoveField(
            model_name='roundtrip',
            name='distance',
        ),
        migrations.RemoveField(
            model_name='roundtrip',
            name='drive',
        ),
        migrations.RemoveField(
            model_name='roundtrip',
            name='driverCharge',
        ),
        migrations.RemoveField(
            model_name='roundtrip',
            name='fare',
        ),
        migrations.RemoveField(
            model_name='roundtrip',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='roundtrip',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='roundtrip',
            name='status',
        ),
        migrations.RemoveField(
            model_name='roundtrip',
            name='total',
        ),
    ]
