# Generated by Django 5.1.6 on 2025-03-06 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_remove_roundtrip_cartype_remove_roundtrip_distance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roundtrip',
            name='round',
        ),
        migrations.AddField(
            model_name='roundtrip',
            name='carType',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='roundtrip',
            name='distance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roundtrip',
            name='drive',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='roundtrip',
            name='driverCharge',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='roundtrip',
            name='fare',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='roundtrip',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='roundtrip',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roundtrip',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='roundtrip',
            name='total',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
