# Generated by Django 5.1.6 on 2025-03-30 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_roundtrip_round_roundtrip_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roundtrip',
            name='drive',
        ),
    ]
